<div class="jumbotron">
    <h1>Example application!</h1>

    <p>
        Select action from menu above.
    </p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Github</h3>
            </div>
            <div class="panel-body">
                <p>
                    <a href="https://github.com/GrzegorzDrozd">See it on github</a>
                </p>
            </div>
        </div>
    </div>
</div>
